name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: convert token
        continue-on-error: true
        run: npm run token-build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: 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
          commit_message: Automated Change